#pragma once
 
#include <ch32v00x.h>

#define GPIO_LCD_PORT GPIOD
#define GPIO_LCD_RS_PIN GPIO_Pin_0
#define GPIO_LCD_E_PIN GPIO_Pin_2
#define GPIO_LCD_D4_PIN GPIO_Pin_3
#define GPIO_LCD_D5_PIN GPIO_Pin_4
#define GPIO_LCD_D6_PIN GPIO_Pin_5
#define GPIO_LCD_D7_PIN GPIO_Pin_6

#define GPIO_ENC_BUTTON_PORT GPIOC
#define GPIO_ENC_BUTTON_PIN GPIO_Pin_4

#define GPIO_ENC_ROT_PORT GPIOA
#define GPIO_ENC_ROT_PORT_SOURCE GPIO_PortSourceGPIOA
#define GPIO_ENC_PHA_PIN GPIO_Pin_2
#define GPIO_ENC_PHA_PIN_SOURCE GPIO_PinSource1
#define GPIO_ENC_PHB_PIN GPIO_Pin_1
#define GPIO_ENC_PHB_PIN_SOURCE GPIO_PinSource2

#define GPIO_I2C_PORT GPIOC
#define GPIO_I2C_SDA_PIN GPIO_Pin_1
#define GPIO_I2C_SCL_PIN GPIO_Pin_2

#define GPIO_SPI_PORT GPIOC
#define GPIO_SPI_SCK_PIN GPIO_Pin_5
#define GPIO_SPI_MOSI_PIN GPIO_Pin_6
#define GPIO_SPI_DDS_CS_PIN GPIO_Pin_3
#define GPIO_SPI_PGA_CS_PIN GPIO_Pin_0

void gpio_init(void);
